### ISSUE TITLE
Disable cameras that have been cloned

### ISSUE THREAD

**Issue by husberg-disguise** [disguise-one/RenderStream-Unity#6]
The Unity application window still renders the view of the (main) camera that has been cloned for streaming. This is a waste of resources, so it should be disabled.

Stretch goal: blit a multi-view of all streams' camera views so the window isn't empty?

**Comment by JehtBlack** [comment]
Due to the way that we get cameras (Camera.allCameras) disabling the object would prevent them being found if we need to recreate streams, so I've opted to set the culling mask of all "template" cameras so that they render nothing, meanwhile the "instance" cameras are set to render everything
Imperfect fix since the concept of a "template camera" doesn't exist in code beyond just "an enabled camera that we didn't instantiate ourselves" this will need to be addressed in future
Fixed with commit: https://github.com/disguise-one/RenderStream-Unity/commit/d15181cf7460601b61931cddacfb54ab6ce4b9cb
